#!/usr/bin/env python3
"""加载 train_svm.py 保存的模型，并在独立验证集上评价。

本文件不会训练或重新拟合模型，不会调用 model.fit()。

运行示例：
    python validate_svm.py --model-input linear_svm.joblib \
        --validation-input validation_features.csv
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate a trained relax/bend Linear SVM."
    )
    parser.add_argument(
        "--model-input",
        type=Path,
        required=True,
        help="Model artifact generated by train_svm.py.",
    )
    parser.add_argument(
        "--validation-input",
        type=Path,
        required=True,
        help="Independent validation feature CSV.",
    )
    parser.add_argument(
        "--metrics-output",
        type=Path,
        help="Optional JSON file for validation metrics.",
    )
    return parser.parse_args()


def load_artifact(path: Path) -> dict:
    """读取模型包，并检查它是否由新版 train_svm.py 生成。"""
    artifact = joblib.load(path)
    required = {
        "model", "features", "c", "training_input",
        "train_windows", "train_trials",
    }
    if not isinstance(artifact, dict) or not required <= set(artifact):
        raise ValueError(
            "Unsupported model file. Retrain it with the current "
            "train_svm.py before validation."
        )
    return artifact


def validate_frame(frame: pd.DataFrame, features: list[str]) -> None:
    """确认验证集包含模型需要的特征、trial_id和两种标签。"""
    required = {"trial_id", "label_id", *features}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(
            f"Validation CSV missing columns: {sorted(missing)}"
        )
    if frame[features].isna().any().any():
        raise ValueError("Validation features contain NaN values.")
    if set(frame["label_id"].unique()) != {0, 1}:
        raise ValueError(
            "Validation label_id must contain both classes 0 and 1."
        )


def main() -> int:
    args = parse_args()
    artifact = load_artifact(args.model_input)
    model = artifact["model"]
    features = list(artifact["features"])

    frame = pd.read_csv(args.validation_input)
    validate_frame(frame, features)
    validation_x = frame[features]
    validation_y = frame["label_id"].to_numpy(dtype=np.int64)

    # 只调用 predict()，不调用 fit()；验证集不会修改任何模型参数。
    prediction = model.predict(validation_x)
    accuracy = accuracy_score(validation_y, prediction)
    balanced = balanced_accuracy_score(validation_y, prediction)
    f1 = f1_score(validation_y, prediction)
    matrix = confusion_matrix(
        validation_y, prediction, labels=[0, 1]
    )
    validation_trials = int(frame["trial_id"].astype(str).nunique())

    print(f"Model input: {args.model_input}")
    print(f"Training input: {artifact['training_input']}")
    print(f"Validation input: {args.validation_input}")
    print(f"Features ({len(features)}): {features}")
    print(
        f"Training windows: {artifact['train_windows']}, "
        f"trials: {artifact['train_trials']}"
    )
    print(
        f"Validation windows: {len(frame)}, "
        f"trials: {validation_trials}"
    )
    print("\nIndependent validation metrics")
    print(f"accuracy: {accuracy:.4f}")
    print(f"balanced_accuracy: {balanced:.4f}")
    print(f"F1: {f1:.4f}")
    print("\nValidation confusion matrix [relax, bend]:")
    print(matrix)
    print("\nValidation classification report:")
    print(classification_report(
        validation_y,
        prediction,
        labels=[0, 1],
        target_names=["relax", "bend"],
        digits=4,
        zero_division=0,
    ))

    if args.metrics_output is not None:
        metrics = {
            "evaluation_mode": "independent_validation",
            "model_input": str(args.model_input),
            "training_input": artifact["training_input"],
            "validation_input": str(args.validation_input),
            "features": features,
            "c": artifact["c"],
            "train_windows": artifact["train_windows"],
            "train_trials": artifact["train_trials"],
            "validation_windows": len(frame),
            "validation_trials": validation_trials,
            "accuracy": float(accuracy),
            "balanced_accuracy": float(balanced),
            "f1": float(f1),
            "confusion_matrix": matrix.tolist(),
        }
        args.metrics_output.parent.mkdir(parents=True, exist_ok=True)
        args.metrics_output.write_text(
            json.dumps(metrics, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print(f"Saved validation metrics: {args.metrics_output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
